### ISSUE TITLE
GetLegalMoves does not comply with the rule amendment

### ISSUE THREAD

**Issue by Johnnei** [Bakkes/Karo#26]
The clarification on the moves which used a tile which temporarily creates a disconnected board is not correctly implemented in the move finder.
The unit test (Added in commit a6f413b11ca342d333181c11064ee7b755d0d9ad) "RulesAmendment" checks a board which could return this move.

**Comment by jkemperman** [comment]
Fixed, the test succeeds now. Everything else seems to behave as expected.
